version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projetospring
      MYSQL_USER: springusr
      MYSQL_PASSWORD: 0609
    ports:
      - "3306:3306"
    networks:
      - spring-network

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-container
    environment:
      SPRING_APPLICATION_NAME: apispring
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/projetospring
      SPRING_DATASOURCE_USERNAME: springusr
      SPRING_DATASOURCE_PASSWORD: 0609
    ports:
      - "8082:8080"
    depends_on:
      - mysql
    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge



